spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=DEBUG
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.datasource.hikari.maximum-pool-size=5
