name: 🔎 PR Title Check

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

permissions:
    contents: read

jobs:
    pr-title:
        runs-on: ubuntu-latest
        steps:
            - name: Validate PR title
              uses: actions-ecosystem/action-regex-match@v2
              with:
                  text: ${{ github.event.pull_request.title }}
                  regex: '^\[(BACKEND|FRONTEND|DEVOPS|DOCUMENT|DOCS|DOCUMENTATION|DATABASE)\]\s*:\s+.+'
